version: '3'
services:
  php:
    ports:
      - 7090:80
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"

  db:
    ports:
      - 33069:3306
